package com.aisandbox.server.cli;

import com.aisandbox.server.cli.pki.PemWriter;
import com.aisandbox.server.cli.pki.SelfSignedServerCertGenerator;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.PosixFilePermissions;
import java.util.concurrent.Callable;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

/**
 * {@code aisandboxctl pki init} — generates the server's self-signed cert
 * + key (RSA 2048), creates the empty allowlist directory, drops a
 * sample {@code config.yaml}. Idempotent: refuses to overwrite existing
 * material unless {@code --force} is given.
 */
@Command(name = "pki", description = "PKI provisioning.", subcommands = PkiInitCommand.Init.class)
public class PkiInitCommand implements Runnable {

    @Override
    public void run() {
        picocli.CommandLine.usage(this, System.out);
    }

    @Command(name = "init", description = "Generate server cert+key, allowlist dir, sample config.")
    public static class Init implements Callable<Integer> {

        @Option(names = "--pki-dir", description = "PKI directory (default /etc/ai-sandbox-server/pki)")
        Path pkiDir = Path.of("/etc/ai-sandbox-server/pki");

        @Option(names = "--clients-dir", description = "Allowlist directory (default /etc/ai-sandbox-server/clients)")
        Path clientsDir = Path.of("/etc/ai-sandbox-server/clients");

        @Option(names = "--config", description = "Config file path (default /etc/ai-sandbox-server/config.yaml)")
        Path configFile = Path.of("/etc/ai-sandbox-server/config.yaml");

        @Option(names = "--cn", description = "Server cert Common Name (default ai-sandbox-server)")
        String cn = "ai-sandbox-server";

        @Option(names = "--force", description = "Overwrite existing PKI material if present.")
        boolean force;

        @Override
        public Integer call() throws Exception {
            ensureDir(pkiDir);
            ensureDir(clientsDir);

            Path crt = pkiDir.resolve("server.crt");
            Path key = pkiDir.resolve("server.key");
            if ((Files.exists(crt) || Files.exists(key)) && !force) {
                System.err.println("Server cert/key already present. Use --force to overwrite.");
                return 2;
            }
            var mat = new SelfSignedServerCertGenerator().generate(cn);
            PemWriter.writeCert(crt, mat.certificate());
            PemWriter.writePrivateKey(key, mat.keyPair().getPrivate());

            if (!Files.exists(configFile)) {
                Files.writeString(configFile, sampleConfigYaml());
                try {
                    Files.setPosixFilePermissions(configFile, PosixFilePermissions.fromString("rw-r--r--"));
                } catch (UnsupportedOperationException ignored) {
                    // best-effort
                }
            }

            System.out.println("PKI initialised:");
            System.out.println("  cert  : " + crt);
            System.out.println("  key   : " + key + "  (mode 0600)");
            System.out.println("  clients: " + clientsDir + "  (mode 0750)");
            System.out.println("  config: " + configFile);
            return 0;
        }

        private static void ensureDir(Path p) throws IOException {
            if (!Files.exists(p)) {
                Files.createDirectories(p);
            }
            try {
                Files.setPosixFilePermissions(p, PosixFilePermissions.fromString("rwxr-x---"));
            } catch (UnsupportedOperationException ignored) {
                // best-effort
            }
        }

        private static String sampleConfigYaml() {
            return """
                    # ai-sandbox-server — generated by `aisandboxctl pki init`.
                    # Every key has a sensible default; uncomment to override.
                    #
                    ai-sandbox:
                      server:
                        tls:
                          port: 12410
                          bind-address: "0.0.0.0"
                        pki:
                          dir: /etc/ai-sandbox-server/pki
                        clients:
                          dir: /etc/ai-sandbox-server/clients
                        hostscripts:
                          repo-root: /opt/ai-sandbox
                        audit:
                          file: /var/log/ai-sandbox-server/audit.log
                          retention-days: 7
                    """;
        }
    }
}
